version: "3.3"
services:
  nginx:
    image: nhhuy/dorm-management-app:nginx-latest
    ports:
      - 80:80
    depends_on: 
      - api
    
  api:
    image: nhhuy/dorm-management-app:api-latest
    restart: always
    ports:
      - 3001:3001

    