version: "3.8"
services:
  nginx:
    build:
      context: ./nginx
      dockerfile: ./Dockerfile
    ports:
      - 80:80
    volumes:
      - ./frontend/build:/usr/share/nginx/html
      - ./default.conf:/etc/nginx/conf.d/default.conf
    image: nhhuy/deploy-test:nginx-latest
  api:
    build:
      context: ./backend
    restart: unless-stopped
    ports:
      - 3001:3001
    expose:
      - 3001
    image: nhhuy/deploy-test:api-latest